In [1]:
from IPython.display import display, HTML
display(HTML("<style>.container { width:85% !important; }</style>"))

In [10]:
import numpy as np
import pandas as pd

# Load the data from the CSV file
data = pd.read_csv('dataB4A3.csv', header=None)
data

0  1
0  1  2
1  2  2
2  1  3
3  4  2
4  5  4

In [11]:
# Extract the x and y values as numpy arrays
x = data.iloc[:, 0].values
y = data.iloc[:, 1].values
print(x)
print(y)

[1 2 1 4 5]
[2 2 3 2 4]


In [12]:
# Calculate the correlation coefficient
corr_coef = np.corrcoef(x, y)[0, 1]
corr_coef

0.4923659639173309

In [13]:
# Construct the design matrix
X = np.column_stack([np.ones_like(x), x, x**2])
X

array([[ 1,  1,  1],
       [ 1,  2,  4],
       [ 1,  1,  1],
       [ 1,  4, 16],
       [ 1,  5, 25]], dtype=int64)

In [ ]:
# Calculate the optimal parameters of the regression polynomial
params = np.linalg.inv(X.T @ X) @ X.T @ y

In [14]:
# Print the correlation coefficient and the optimal parameters
print(f'Correlation coefficient: {corr_coef:.3f}')
print(f'Regression polynomial: y = {params[0]:.3f} + {params[1]:.3f}x + {params[2]:.3f}x^2')


Correlation coefficient: 0.492
Regression polynomial: y = 4.281 + -2.105x + 0.404x^2


In [15]:
import numpy as np

# Daten einlesen
data = np.array([[1,2],[2,2],[1,3],[4,2],[5,4]])

# Designmatrix aufstellen
X = np.ones((data.shape[0], 2))
X[:,1] = data[:,0]**2

# Zielwerte definieren
y = data[:,1]

# Berechnung der optimalen Parameter theta
theta = np.linalg.inv(X.T @ X) @ X.T @ y

# Ausgabe der optimalen Parameter und der Regressionsfunktion
print('Optimale Parameter theta:', theta)
print('Regressionsfunktion: y = {:.2f} + {:.2f}x^2'.format(theta[0], theta[1]))

Optimale Parameter theta: [2.1312336  0.04986877]
Regressionsfunktion: y = 2.13 + 0.05x^2
