In [7]:
import numpy as np

# Daten einlesen
data = np.array([[0,6],[1,3],[2,2],[3,1],[4,2],[5,4]])
data

array([[0, 6],
       [1, 3],
       [2, 2],
       [3, 1],
       [4, 2],
       [5, 4]])

In [8]:
# Designmatrix aufstellen
X = np.ones((data.shape[0], 2))
X[:,1] = data[:,0]**2
X

array([[ 1.,  0.],
       [ 1.,  1.],
       [ 1.,  4.],
       [ 1.,  9.],
       [ 1., 16.],
       [ 1., 25.]])

In [9]:
# Zielwerte definieren
y = data[:,1]
y

array([6, 3, 2, 1, 2, 4])

In [10]:
# Berechnung der optimalen Parameter theta
theta = np.linalg.inv(X.T @ X) @ X.T @ y
theta

array([ 3.25096525, -0.02737803])

In [11]:
# Ausgabe der optimalen Parameter und der Regressionsfunktion
print('Regressionsfunktion: y = {:.2f} + {:.2f}x^2'.format(theta[0], theta[1]))

Regressionsfunktion: y = 3.25 + -0.03x^2
