In [2]:
import numpy as np

# Daten einlesen
data = np.array([[1,2],[2,2],[1,3],[4,2],[5,4]])
data

array([[1, 2],
       [2, 2],
       [1, 3],
       [4, 2],
       [5, 4]])

In [3]:
# Designmatrix aufstellen
X = np.ones((data.shape[0], 2))
X[:,1] = data[:,0]**2
X

array([[ 1.,  1.],
       [ 1.,  4.],
       [ 1.,  1.],
       [ 1., 16.],
       [ 1., 25.]])

In [4]:
# Zielwerte definieren
y = data[:,1]
y

array([2, 2, 3, 2, 4])

In [5]:
# Berechnung der optimalen Parameter theta
theta = np.linalg.inv(X.T @ X) @ X.T @ y
theta

array([2.1312336 , 0.04986877])

In [6]:
# Ausgabe der optimalen Parameter und der Regressionsfunktion
print('Regressionsfunktion: y = {:.2f} + {:.2f}x^2'.format(theta[0], theta[1]))

Regressionsfunktion: y = 2.13 + 0.05x^2
