In [1]:
from IPython.display import display, HTML
display(HTML("<style>.container { width:85% !important; }</style>"))

In [16]:
import numpy as np
import pandas as pd

# Load the data from the CSV file
data = pd.read_csv('dataB4A3.csv', header=None)
data

0  1
0  0  6
1  1  3
2  2  2
3  3  1
4  4  2
5  5  4

In [17]:
# Extract the x and y values as numpy arrays
x = data.iloc[:, 0].values
y = data.iloc[:, 1].values
print(x)
print(y)

[0 1 2 3 4 5]
[6 3 2 1 2 4]


In [18]:
corr_coef = np.corrcoef(x, y)
corr_coef

array([[ 1.        , -0.41833001],
       [-0.41833001,  1.        ]])

In [19]:
# Calculate the correlation coefficient
corr_coef_xy = np.corrcoef(x, y)[0, 1]
corr_coef_xy

-0.41833001326703784

In [20]:
# Construct the design matrix
X = np.column_stack([np.ones_like(x), x, x**2])
X

array([[ 1,  0,  0],
       [ 1,  1,  1],
       [ 1,  2,  4],
       [ 1,  3,  9],
       [ 1,  4, 16],
       [ 1,  5, 25]], dtype=int64)

In [21]:
# Calculate the optimal parameters of the regression polynomial
params = np.linalg.inv(X.T @ X) @ X.T @ y
params

array([ 5.96428571, -3.34642857,  0.58928571])

In [22]:
# Print the correlation coefficient and the optimal parameters
print(f'Correlation coefficient: {corr_coef_xy:.3f}')
print(f'Regression polynomial: y = {params[0]:.3f} + {params[1]:.3f}x + {params[2]:.3f}x^2')

Correlation coefficient: -0.418
Regression polynomial: y = 5.964 + -3.346x + 0.589x^2


In [27]:
#A4

In [31]:
X_new = np.column_stack([np.ones_like(x), (x-3)**2])
X_new

array([[1, 9],
       [1, 4],
       [1, 1],
       [1, 0],
       [1, 1],
       [1, 4]], dtype=int64)

In [32]:
params_new = np.linalg.inv(X_new.T @ X_new) @ X_new.T @ y
params_new

array([1.32522796, 0.52887538])

In [35]:
# Print the correlation coefficient and the optimal parameters
print(f'Regression polynomial: y = {params_new[0]:.3f} + {params_new[1]:.3f}(x-3)^2')

Regression polynomial: y = 1.325 + 0.529(x-3)^2
